### ISSUE TITLE
Auto-reply to texts

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-api#2] opened 2020-03-26 21:02 UTC
Since replies are un-monitored, we should respond to texts telling the patient to call instead.

**Comment by RachelWiens** [comment] 2020-04-05 01:07
Unassigning myself as mentioned in the Slack, since I wasn't able to make as much progress with this as I hoped during the week since I'm not familiar with Docker and several of the other frameworks this app is using. Sorry about that!

Steve confirmed that the existing reply mechanism seems to work. Future improvements that could be done to it:
* Matching the response to the language of the user.
* Rate-limiting to prevent spammers.
* Based on  comparing the Twilio docs to the currently implemented method, I suspect that the current implementation could be simplified. Relevant docs: https://www.twilio.com/docs/sms/quickstart/node?code-sample=code-send-an-sms-using-twilio-with-nodejs&code-language=Node.js&code-sdk-version=3.x#receive-and-reply-to-inbound-sms-messages-with-express

**Comment by iamstevedavis** [comment] 2020-04-23 03:40
I believe this was resolved by https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-api/pull/24

**Closed by iamstevedavis** 2020-04-23 03:40 UTC
Labels: enhancement
