### ISSUE TITLE
Resolve Backend Issues for Frontend

### ISSUE THREAD

**Issue by iamstevedavis** [SanctuaryRefugeeHealth/sanctuary-patient-api#27] opened 2020-04-11 04:30 UTC
From @jaeyp 
1. Update DB enum and seeder with top 5 languages
["english", "arabic", "spanish", "tigrinya", "somali", "turkish"]
2. Add a new api to get appointment details
e.g. api.get("/appointments/:appointmentId", getAppointment);
3. Add a new api to delete an appointment
e.g. api.delete("/appointments/:appointmentId", deleteAppointment);
4. Add a new api to get all "sent" and "replied" messages at once, or alter an existing api.
e.g. api.get("/appointments/:appointmentId/messages", getMessages);
5. RangeError [ERR_HTTP_INVALID_STATUS_CODE] occured with some api (e.g. patchAppointments)
I'm using Express version 4.17.1 and I had to use res.sendStatus() instead of res.send() to avoid this error.
This is weird because I'm using Express 4 not 5, and res.send() with status number is deprecated in Express 5.
https://expressjs.com/en/guide/migrating-5.html#res.send.status

**Comment by iamstevedavis** [comment] 2020-04-11 04:31
I can tackle this. Couple questions for you. For #4, we already have that API. Could you break down a bit more what you want? I assume you want all the data from the "messages" and "replies" column but how do you want that data to look? I am worried this could become a very large request very quickly without something like pagination and I don't really want to implement that right now... is there another way? Regarding #5... I don't think we use that anywhere except one spot where I have fixed it in my PR... we use res.status(status).send(obj) which I think still functions as expected in Express 5. Maybe we have an issue with error handling on that route? Could you give me a bit more detail? I added isDeleted to appointments, will that still work for messages on your end? For example, if you call the route to get messages and pass in an appointmentId that has been deleted, do you still want to get those messages?

**Comment by jaeyp** [comment] 2020-04-11 05:24
**For #4**, the reason that I asked the API is becuase Frontend app is showing its dummy data in that way. check this [screenshot](https://user-images.githubusercontent.com/9454987/79035693-f8534280-7b8e-11ea-9f47-145362b98ffa.png). it shows messages that is sent by Sanctuary and replied by patient together. and all messages just belongs to one appointment with ID, so I don't think this make a very large request. 
As I said, I just suggested this changes by referencing current Frontend app and its dummy data. and I agree with you for MVP, we can discuss it later.

**For #5** the situation that I got the error (ERR_HTTP_INVALID_STATUS_CODE) is as below.
I implemented an appointment confirm button.
when the button's clinked, it send axios.patch(`/appointments/${id}`, { isConfirmed }, header w/ token) (of course, id is valid)
but this axios.patch() is not returned and responded from server.
server is stuck with the request showing this error messages below
```
sanctuary-api | src-0  | Fri, 10 Apr 2020 18:38:33 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at src/api/handlers/appointments/patchAppointments.js:27:23
sanctuary-api | src-0  | RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 1
sanctuary-api | src-0  |     at ServerResponse.writeHead (_http_server.js:241:11)
sanctuary-api | src-0  |     at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:44:26)
sanctuary-api | src-0  |     at ServerResponse._implicitHeader (_http_server.js:232:8)
sanctuary-api | src-0  |     at ServerResponse.end (_http_outgoing.js:720:10)
sanctuary-api | src-0  |     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
sanctuary-api | src-0  |     at /app/src/api/handlers/appointments/patchAppointments.js:18:25 {
sanctuary-api | src-0  |   code: 'ERR_HTTP_INVALID_STATUS_CODE'
```
After I modified /api/handlers/appointments/patchAppointments.js as below, then it works
```javascript
export default (req, res) => {
  const { appointmentId } = req.params;

  const { isConfirmed } = req.body;

  db("appointments")
    .where({ appointmentId })
    .update({ appointmentIsConfirmed: isConfirmed })
    .then(result => {
      //res.status(201).send(result);    // fail with ERR_HTTP_INVALID_STATUS_CODE
      //res.status(200).send(result);    // fail with ERR_HTTP_INVALID_STATUS_CODE
      //res.status("200").send(result);  // fail with ERR_HTTP_INVALID_STATUS_CODE
      res.sendStatus(201).send(result);  // it works
    });
};
```
let me know if you need more information! thanks!

**Comment by iamstevedavis** [comment] 2020-04-12 19:32
@jaeyp I added a route called communications that looks like the following. Does this work for you?

`localhost:80/api/communications/:appointmentId`

```
{
    "messages": [
        {
            "messageId": 33,
            "appointmentId": 78,
            "templateName": "Appointment Reminder",
            "messageBody": "Hello,               this is a message from Dr. Michael Stephenson's office for {{patientName}}.               You have an appointment with Dr. {{practitionerClinicName}} on {{appointmentTime}}               at the following address {{practitionerAddress}}.",
            "timeSent": "2020-04-12T15:13:49.000Z",
            "language": "somali"
        }
    ],
    "replies": [
        {
            "replyId": 11,
            "phoneNumber": "555-555-5555",
            "body": "Thank you for the reminder!",
            "appointmentId": 78,
            "time": "2020-04-12T15:13:49.000Z"
        }
    ]
}
```

**Comment by jaeyp** [comment] 2020-04-12 20:32
I think it's good enough for showing message history. I will update app and double check when it's merged. thanks!

**Closed** 2020-04-15 04:14 UTC
